services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    init: true
    ports:
      - "3000:3000"
    volumes:
      - .:/home/user/workspace/axum_minimum
      - target_volume:/home/user/workspace/axum_minimum/target

volumes:
  target_volume:
